basedns: "mzinga.io"
tenant:
  name: "newesiscorporate"
  tier: "pro"
  site:
    title: "Newesis Srl – DevOps and Cloud Engineering Services – Be Professional Have Fun !"
    titleSuffix: "Newesis Srl - Be Professional Have Fun !"
    description: "Newesis Srl Corporate Web Site – DevOps and Cloud Engineering Services – DevOps as a Service – Managed Kubernetes Platform"
    cardList: "services=Our Services||people=Our People||projects=Our Projects"
    topCardList:
      title: "Our Services"
      tag: "services"
    bottomCardList:
      title: "Our People"
      tag: "people"
    cardLists: "services=Our Services||people=Our People||projects=Our Projects"
    topPage:
      title: "About Us"
      slug: "about-us"
      uri: "/about-us"
    formPage:
      title: "Contact Us"
      slug: "contact-us"
      uri: "/contact-us"
nodePool:
  # priority: "Spot" # To be set to force deployment in spot instances
  spot:
    tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
sampleFrontend:
  enabled: true
  name: newesis-sample-fe
  hostName: www.newesis.com
  replicas: 1
  image: newesissrl.azurecr.io/newesis/website/frontend # Placeholder value
  imageTag: 0.1.23 # Placeholder value
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: mzinga.io/tenants
                operator: In
                values:
                  - "true"
