name: Test Azure Login
on:
  push:
    branches: ['feat/deploy']

jobs:

  login:
    runs-on: ubuntu-latest
    environment: newesis-frontend
    steps:
    - uses: azure/setup-kubectl@v3
      with:
        version: 'v1.25.11'
      id: installkubectl
    - uses: azure/setup-helm@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      id: installhelm
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account show
